mapfusion:
    solid:
        knn_feature_dim: 40
        max_range: 80
        num_sector: 60
        num_height: 64
        num_nearest_matches: 50
        num_match_candidates: 1
        fov_up: 2.0
        fov_down: -24.8

    interRobot:
        #topic
        solid_topic: "solid"
        solid_frame: "base_link"
        local_topic: "liorf/mapping/cloud_info"

        #thres
        loop_threshold: 0.2 #
        pcm_threshold: 20
        icp_threshold: 3
        loop_frame_threshold: 10 #frames
        pcm_start_threshold: 5   # 5 for best result, 2 for work in harsh environment

        robot_initial: jackal0
        use_position_search: false #use position search may introduce more global loop closure, but spend more time for candidate checking
